import {
  ArtDetail,
  CadastroAgencia,
  CadastroArte,
  CadastroCampanha,
  CadastroCategoria,
  CadastroEventos,
  CadastroFornecedor,
  CadastroFotografo,
  CadastroImagens,
  CadastroLoja,
  CadastroMarca,
  CadastroProduto, Dashboard,
  Error404,
  Hub,
  ImgDetail,
  ListOrders,
  ListUser,
  Login,
  Marcas,
  OrderDetail,
  Orders,
  SearchArt,
  SearchEvent,
  SearchImages
} from "@pages";
import { RoutesList } from "@types";

export const routes: RoutesList[] = [
  {
    path: "/",
    component: Error404,
    isPublic: true,
    title: "Não encontrado",
    id: 1,
  },
  {
    path: "/login",
    component: Login,
    isPublic: true,
    title: "Login",
    id: 2,
  },
  {
    path: "/marcas",
    component: Marcas,
    isPublic: true,
    title: "Selecione a marca",
    id: 3,
  },
  {
    path: "/listagem-usuario",
    component: ListUser,
    isPublic: true,
    title: "Listagem de usuário",
    id: 4,
    visibleMenu: true,
  },
  {
    path: "/cadastro-marcas",
    component: CadastroMarca,
    isPublic: true,
    title: "Cadastro de marca",
    id: 5,
    visibleMenu: false,
  },
  {
    path: "/cadastro-lojas",
    component: CadastroLoja,
    isPublic: true,
    title: "Cadastro de lojas",
    id: 6,
    visibleMenu: false,
  },
  {
    path: "/cadastro-agencia",
    component: CadastroAgencia,
    isPublic: true,
    title: "Cadastro de agência",
    id: 7,
    visibleMenu: false,
  },
  {
    path: "/home/:marca",
    component: Dashboard,
    isPublic: true,
    title: "Home",
    id: 8,
  },
  {
    path: "/cadastro-campanha/:marca",
    component: CadastroCampanha,
    isPublic: true,
    title: "Cadastro de campanha",
    id: 9,
    visibleMenu: false,
  },
  {
    path: "/cadastro-arte/:marca",
    component: CadastroArte,
    isPublic: true,
    title: "Cadastro de arte",
    id: 10,
    visibleMenu: false,
  },
  {
    path: "/cadastro-fotografo",
    component: CadastroFotografo,
    isPublic: true,
    title: "Cadastro de agência de fotografia",
    id: 11,
    visibleMenu: false,
  },
  {
    path: "/cadastro-imagem/:marca",
    component: CadastroImagens,
    isPublic: true,
    title: "Cadastro de Imagens",
    id: 12,
    visibleMenu: false,
  },
  {
    path: "/detalhe-imagem/:marca/:id",
    component: ImgDetail,
    isPublic: true,
    title: "Detalhe da Imagem",
    id: 13,
  },
  {
    path: "/hub",
    component: Hub,
    isPublic: true,
    title: "HUB",
    id: 14,
  },
  {
    path: "/busca-imagens/:marca",
    component: SearchImages,
    isPublic: true,
    title: "Busca de imagens",
    id: 15,
    visibleMenu: true,
  },
  {
    path: "/cadastro-categoria/:marca",
    component: CadastroCategoria,
    isPublic: true,
    title: "Cadastro categoria",
    id: 16,
    visibleMenu: false,
  },
  {
    path: "/cadastro-produto/:marca",
    component: CadastroProduto,
    isPublic: true,
    title: "Cadastro produto",
    id: 17,
    visibleMenu: false,
  },
  {
    path: "/busca-artes/:marca",
    component: SearchArt,
    isPublic: true,
    title: "Busca de artes",
    id: 18,
    visibleMenu: true,
  },
  {
    path: "/detalhe-arte/:marca/:id",
    component: ArtDetail,
    isPublic: true,
    title: "Detalhe da Arte",
    id: 19,
  },
  {
    path: "/cadastro-evento/:marca",
    component: CadastroEventos,
    isPublic: true,
    title: "Cadastro de Eventos",
    id: 20,
    visibleMenu: true,
  },
  {
    path: "/busca-evento/:marca",
    component: SearchEvent,
    isPublic: true,
    title: "Busca de Eventos",
    id: 21,
    visibleMenu: true,
  },
  {
    path: "/pedido/:marca",
    component: Orders,
    isPublic: true,
    title: "Fazer pedido",
    id: 22,
    visibleMenu: true,
  },
  {
    path: "/pedido/:marca/lista",
    component: ListOrders,
    isPublic: true,
    title: "Lista de pedidos",
    id: 23,
    visibleMenu: true,
  },
  {
    path: "/pedido/:marca/:id",
    component: OrderDetail,
    isPublic: true,
    title: "Detalhe de pedido",
    id: 24,
    visibleMenu: false,
  },
  {
    path: "/cadastro-fornecedor/:marca",
    component: CadastroFornecedor,
    isPublic: true,
    title: "Cadastro de fornecedor",
    id: 25,
    visibleMenu: true,
  },
];
